### ISSUE TITLE
Improve startup instructions for novices

### ISSUE THREAD

**Issue by JoostvanPinxten** [DSLFoundry/mps-plaintextgen#43]
If a user is not so familiair with the MPS generator structure, it can be a challenge to figure out where the right entry points are located. 

Describe a very simple start, assuming that the user has no experience with generators. Starting from the root mapping, and showing some of the intentions that make it possible to add fields, and loop over elements in the generator.

**Comment by eugenschindler** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/183)
